name: Coverage Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    name: PHPUnit Coverage Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, sodium
          ini-values: error_reporting=-1, display_errors=On
          coverage: xdebug

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v3"

      - name: PHPUnit tests with coverage
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Check for 100% coverage
        uses: michaelpetri/phpunit-coverage-check@0.3.1
        with:
          clover-file: build/logs/clover.xml
          min-coverage: 100
